[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_dapp_vote = "4AEtDMG3A5rFTFwj6KyA6K41dxxpagemC4CaG5w9oABc"

[programs.devnet]
solana_dapp_vote = "4AEtDMG3A5rFTFwj6KyA6K41dxxpagemC4CaG5w9oABc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "pollisol.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
